import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const roboto = Roboto({
  weight: ["400", "500", "700"], // မင်းသုံးချင်တဲ့ အထူအပါးတွေကို ရွေးပါ
  subsets: ["latin"],            // အင်္ဂလိပ်စာအတွက် latin ကို သုံးပါ
  display: "swap",
  variable: "--font-roboto",     // CSS variable အနေနဲ့ သုံးချင်ရင် သတ်မှတ်ပါ
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${roboto.className}`}>{children}</body>
    </html>
  );
}
